### ISSUE TITLE
tr works only at compile time

### ISSUE THREAD

**Issue by trikko** [veelo/gettext#2]
Hi Bastiaan,
I need to translate some strings using gettext format. 
Some of these string are not inside the D code, but in another file I'm loading at runtime. The file is parsed and then I have a list of strings to translate, but `tr` of course works only at compile-time. 

Am I missing something?

**Comment by veelo** [comment]
Hi Andrea,

There are two aspects of this package: string extraction and string translation. String extraction happens at compile time in the `xgettext` configuration and generates a template (.pot) to be processed and completed by a human translator (or AI). String translation happens at runtime, which involves a lookup in the table produced by the human translator.

Regarding the extraction aspect: Is this file you are loading available at compile time? In that case it may be possible to do some trickery in a `version(xgettext)` block so that the strings in that file are extracted together with the strings in the source files. Or [import](https://dlang.org/spec/expression.html#import_expressions) and parse it in a source file that is only part of the `xgettext` configuration. If on the other hand strings in that file are generated at a later date, the translation tables for those strings will have to be generated at a later date also and read in separately. The GNU Gettext utilities can merge various tables if necessary.

Regarding the lookup aspect (where `version != xgettext`) the `tr!(key)` template reduces to the `TranslatableString(key)` struct constructor, and this struct, when evaluated, does the lookup. So my hunch is that if you write `TranslatableString` instead of `tr!` for the keys that are not known at compile time, you omit the extraction aspect but get the lookup aspect. But then you might as well just use the [mofile](https://mofile.dpldocs.info/v0.2.1/mofile.MoFile.html) package directly.

So are the contents of the file known at compile time, or generated afterwards?

**Comment by trikko** [comment]
For example, I have an HTML file with some elements marked with a data-translate attribute. I have a separate program that parses the HTML and generates the POT file.

Essentially, I'm not interested in extracting strings from the D code because there aren't any, but I need to translate the HTML I will receive (at runtime!)

**Comment by trikko** [comment]
You're right about mofile package, I didn't find it on my search. Thank you :)
